apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: mongodb
  labels:
    type: db
spec:
  clusterIP: None
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    type: db