apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-init
  namespace: mongodb
spec:
  backoffLimit: 5
  template:
    spec:
      serviceAccountName: default
      restartPolicy: Never
      containers:
      - name: mongo-init
        image: mongo:6.0
        command:
        - /bin/bash
        - -c
        - |
          # Wait for all pods to be ready
          sleep 10
          
          # Initialize replica set
          mongosh --host mongodb-0.mongo-service.mongodb.svc.cluster.local:27017
          --eval "
              rs.initiate({
                _id: 'rs0',
                members: [
                  { _id: 0, host: 'mongodb-0.mongo-service.mongodb.svc.cluster.local:27017' },
                  { _id: 1, host: 'mongodb-1.mongo-service.mongodb.svc.cluster.local:27017' },
                  { _id: 2, host: 'mongodb-2.mongo-service.mongodb.svc.cluster.local:27017' }
                ]
              })
            " || true
